

% mkdir(sungridPath)

commandTmp  = sprintf('%s 0 %s %s %s',exePath,configPath,treePathTmp,trainPathTmp);

textE = {
'#! /bin/sh \n'
'echo ' 
commandTmp 
'\n'
commandTmp
'\n'
};

fid = fopen(sungridTrainingPath,'w');
for i=1:length(textE)
    fprintf(fid,[textE{i} ]);
end
fclose(fid);

system(['chmod 755 ' sungridTrainingPath])

%%

text1 = {'#!/bin/sh\n'
    '# Sun Grid file generated by writeSungridEvalue.m\n'
    '#\n'
    '#(the running time for this job)\n'
    '#$ -l h_rt=01:00:00\n'
    '#\n'
    '#(the maximum memory usage of this job)\n'
    '#$ -l h_vmem=20G\n'
    '#\n'
    '#(stderr and stdout are merged together to stdout)\n'
    '#$ -j y\n'
    '#\n'
    '#(reserve memory for the job)\n'
    '#$ -R y\n'
    '#\n'
    '# schedule 389 jobs with ids 1-389\n'
    '#$ -t 1-4\n'
    '#$ -pe multicore 7\n'
    '#$ -o /dev/null\n'
    '#$ -cwd\n'
    '# call your calculation executable\n'
    sungridTrainingPath
    '  ' 
    };

%%

 for s =mriSubjects
    
        
        text2=[num2str(s)  ' $SGE_TASK_ID'];
        
        fid = fopen(sungridTrainingPaths{s},'w');

        for i=1:length(text1)
            fprintf(fid,text1{i});
        end
        
        fprintf(fid,text2);
        fclose(fid);

    
end
