


featuresName = sprintf('%s%d',sprintf('%d ',features(1:end-1)),features(end));


file = [
sprintf('____Path to images index file\n%s\n',randomForestPath),...
sprintf('____Path to folders containing the trees\n%s\n','treeFolder'),...
sprintf('____Number of trees\n%d\n',nTrees),...
sprintf('____Number of testscd\n%d\n',nTests),...
sprintf('____Max depth\n%d\n',maxDepth),...
sprintf('____Min samples per Node\n%d\n',minSamplesPerNode),...
sprintf('____Samples per Tree\n%d\n',3000),...
sprintf('____Patches Per Sample\n%d\n',10),...
sprintf('____Face Size\n%d\n',patchSize),...
sprintf('____Patch Size Ratio\n%d\n',1),...
sprintf('____Feature\n%s',featuresName),...
];


fid = fopen(configPath,'w');
fprintf(fid,'%s',file);
fclose(fid);

