

function writeRegistrationRotationSungridMissed(cycles,cycleRegPath_missed,filePath)

lines ={
'#!/bin/bash'
'# Sun Grid file generated by writeRegistrationSungrid.m'
'#'
'#(the running time for this job)'
'#$ -l h_rt=5:00:00'
'#'
'#(the maximum memory usage of this job)'
'#$ -l h_vmem=2G'
'#'
'#(stderr and stdout are merged together to stdout)'
'#$ -j y'
'#'
'#(reserve memory for the job)'
'#$ -R y'
'#'
'# schedule 389 jobs with ids 1-389'
['#$ -t ' num2str(1) '-' num2str(length(cycles))]
'#$ -o /dev/null'
'#$ -cwd'
'# call your calculation executable'
['array=(' num2str(cycles) ')']
[cycleRegPath_missed '${array[${SGE_TASK_ID}-1]}.sh']
};




fid=fopen(filePath,'w');
for i=1:length(lines)
    fprintf(fid,lines{i});
    fprintf(fid,'\n');
end


fclose(fid);

unix(['chmod 755 ' filePath]);